import { motion } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import { marked } from 'marked'
import anser from 'anser'
import {
  Download, FileText, TrendingUp, DollarSign, Package,
  CheckCircle2, XCircle, ExternalLink, Loader2, Terminal,
} from 'lucide-react'
import { useState, useRef, useEffect } from 'react'

interface CrawlResultCardProps {
  job: {
    id: string
    status: string
    query: string
    output: string
  }
}

function parseOutput(raw: string) {
  const clean = anser.ansiToText(raw)
  const finalMatch = clean.match(/FINAL ANSWER[\s\S]*?═+\s*([\s\S]*?)(?:═{3,}|\[PAYCRAWL\]|Budget:)/i)
  let report = finalMatch?.[1]?.trim() || ''
  if (!report) {
    const synthMatch = clean.match(/PHASE 4[\s\S]*?(?:FINAL ANSWER)?([\s\S]*?)$/i)
    report = synthMatch?.[1]?.trim() || ''
  }
  // Strip terminal box characters and leading junk
  report = report.replace(/^[╝╚╔╗║╠╣╫╪─━┅┄⎯╌╌═]+\s*/gm, '').replace(/^\s*[╝╚╔╗║╠╣╫╪─━┅┄⎯╌╌═]+\s*$/gm, '').trim()
  // Remove duplicate title lines that leak from terminal
  report = report.replace(/^(🔮\s*PayCrawl|Generated by Venice|════|───).*$/gm, '').replace(/^\n+/, '').trim()

  const purchases: { resource: string; cost: string; status: 'buy' | 'skip'; txHash?: string }[] = []
  const buyMatches = clean.matchAll(/✅\s+BUY\s+([\S]+)\s+@\s+\$([\d.]+)/g)
  for (const m of buyMatches) purchases.push({ resource: m[1], cost: m[2], status: 'buy' })
  const skipMatches = clean.matchAll(/❌\s+SKIP\s+([\S]+)/g)
  for (const m of skipMatches) purchases.push({ resource: m[1], cost: '0', status: 'skip' })

  const txHashes = [...clean.matchAll(/(?:txHash|tx|hash)[:\s]*(0x[a-fA-F0-9]{64})/gi)].map(m => m[1])
  const explorerHashes = [...clean.matchAll(/basescan\.org\/tx\/(0x[a-fA-F0-9]{64})/gi)].map(m => m[1])
  const allHashes = [...new Set([...txHashes, ...explorerHashes])]
  if (allHashes.length > 0 && purchases.length > 0) {
    purchases.forEach((p, i) => { if (p.status === 'buy' && allHashes[i]) p.txHash = allHashes[i] })
  }

  const spentMatch = clean.match(/\$([\d.]+)\s*\/\s*\$([\d.]+)/g)
  const spentLine = spentMatch?.[spentMatch.length - 1] || ''
  const totalSpent = spentMatch?.[spentMatch.length - 1]?.match(/\$([\d.]+)\s*\//)?.[1] || '0.00'
  const totalBudget = spentMatch?.[spentMatch.length - 1]?.match(/\/\s*\$([\d.]+)/)?.[1] || '0.00'

  const phases: { name: string; icon: string }[] = []
  const phaseMatches = [...clean.matchAll(/PHASE\s+(\d+):\s*(\w+)\s*AGENT/gi)]
  for (const m of phaseMatches) phases.push({ name: m[2], icon: ['', '🧭', '💰', '🔬', '✍️'][parseInt(m[1])] || '⚙️' })

  return { report, purchases, spentLine, cleanText: clean, totalSpent, totalBudget, phases, txHashes: allHashes }
}

function explorerTxUrl(txHash: string) { return `https://basescan.org/tx/${txHash}` }
function shortHash(hash: string) { return `${hash.slice(0, 10)}...${hash.slice(-6)}` }

function downloadPDF(markdownText: string, filename: string) {
  // Convert markdown → HTML with proper table rendering
  marked.setOptions({ breaks: true, gfm: true })
  const htmlBody = marked.parse(markdownText)
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`
    <html><head><title>${filename}</title>
    <style>
      * { box-sizing: border-box; }
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 850px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; line-height: 1.7; font-size: 14px; }
      .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #0066ff; }
      .header h1 { font-size: 26px; margin: 0 0 5px; color: #0066ff; }
      .meta { color: #888; font-size: 12px; }
      h1 { font-size: 22px; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; margin-top: 36px; }
      h2 { color: #0066ff; font-size: 18px; margin-top: 28px; }
      h3 { color: #333; font-size: 15px; margin-top: 22px; }
      h4 { font-size: 13px; color: #555; }
      p { margin: 10px 0; }
      ul, ol { padding-left: 24px; }
      li { margin: 4px 0; }
      table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 13px; }
      th { border: 1px solid #ccc; padding: 8px 12px; text-align: left; background: #f0f4ff; font-weight: 600; }
      td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
      tr:nth-child(even) { background: #fafafa; }
      blockquote { border-left: 3px solid #0066ff; margin: 15px 0; padding: 10px 20px; background: #f8faff; color: #444; }
      code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; font-size: 13px; font-family: 'SF Mono', monospace; }
      strong { font-weight: 700; }
      hr { border: none; border-top: 2px solid #e0e0e0; margin: 24px 0; }
      a { color: #0066ff; }
      @media print { body { max-width: none; padding: 20px; } .no-print { display: none; } }
    </style></head><body>
    <div class="header">
      <h1>🔮 PayCrawl — Research Report</h1>
      <p class="meta">Generated by Venice AI Agent Pipeline • ${new Date().toLocaleString()}</p>
    </div>
    ${htmlBody}
    </body></html>`)
  win.document.close()
  setTimeout(() => { win.print() }, 500)
}

export function CrawlResultCard({ job }: CrawlResultCardProps) {
  const parsed = parseOutput(job.output || '')
  const isCompleted = job.status === 'completed'
  const isFailed = job.status === 'failed'
  const isRunning = job.status === 'running'
  const hasOutput = job.output && job.output.length > 0
  const consoleRef = useRef<HTMLDivElement>(null)

  // Auto-scroll console to bottom when new output arrives
  useEffect(() => {
    if (consoleRef.current) {
      consoleRef.current.scrollTop = consoleRef.current.scrollHeight
    }
  }, [job.output])

  if (isFailed) {
    return (
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
        className="glass rounded-2xl overflow-hidden border border-red-500/20">
        <div className="bg-red-500/10 px-5 py-4 flex items-center gap-3">
          <XCircle className="w-5 h-5 text-red-400" />
          <div>
            <p className="text-sm font-bold text-white">Crawl Failed</p>
            <p className="text-xs text-red-400">{job.id}: "{job.query}"</p>
          </div>
        </div>
        <div className="p-4 max-h-60 overflow-auto">
          <pre className="text-[11px] text-red-300 font-mono whitespace-pre-wrap">{job.output?.slice(-1000)}</pre>
        </div>
      </motion.div>
    )
  }

  const purchased = parsed.purchases.filter(p => p.status === 'buy')
  const skipped = parsed.purchases.filter(p => p.status === 'skip')

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
      className="space-y-4">

      {/* ═══ Pipeline + Stats Row ═══ */}
      <div className="glass rounded-2xl p-4">
        <div className="flex items-center justify-between flex-wrap gap-3">
          {/* Pipeline phases */}
          {parsed.phases.length > 0 && (
            <div className="flex items-center gap-1.5 flex-wrap">
              {parsed.phases.map((phase, i) => (
                <div key={i} className="flex items-center gap-1">
                  <div className={`flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-medium ${
                    isRunning && i === parsed.phases.length - 1
                      ? 'bg-yellow-500/10 text-yellow-400'
                      : 'bg-emerald-500/10 text-emerald-400'
                  }`}>
                    <span>{phase.icon}</span>
                    <span className="capitalize">{phase.name}</span>
                    {!(isRunning && i === parsed.phases.length - 1) && <CheckCircle2 className="w-2.5 h-2.5" />}
                    {isRunning && i === parsed.phases.length - 1 && <Loader2 className="w-2.5 h-2.5 animate-spin" />}
                  </div>
                  {i < parsed.phases.length - 1 && <span className="text-surface-600 text-[10px]">→</span>}
                </div>
              ))}
            </div>
          )}

          {/* Stats badges */}
          <div className="flex items-center gap-2">
            <span className="flex items-center gap-1 px-2 py-1 rounded-lg bg-emerald-500/10 text-emerald-400 text-[10px] font-bold">
              <Package className="w-3 h-3" /> {purchased.length} BUY
            </span>
            {skipped.length > 0 && (
              <span className="flex items-center gap-1 px-2 py-1 rounded-lg bg-red-500/10 text-red-400 text-[10px] font-bold">
                <XCircle className="w-3 h-3" /> {skipped.length} SKIP
              </span>
            )}
            <span className="flex items-center gap-1 px-2 py-1 rounded-lg bg-brand-500/10 text-brand-400 text-[10px] font-bold">
              <DollarSign className="w-3 h-3" /> ${parsed.totalSpent}/${parsed.totalBudget}
            </span>
          </div>
        </div>
      </div>

      {/* ═══ Purchase Log (on-chain) ═══ */}
      {(purchased.length > 0 || skipped.length > 0) && (
        <div className="glass rounded-2xl p-5">
          <h3 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            On-Chain Payment Log
          </h3>
          <div className="space-y-2">
            {purchased.map((p, i) => (
              <div key={i} className="flex items-center gap-3 bg-emerald-500/5 border border-emerald-500/10 rounded-xl p-3">
                <div className="w-7 h-7 rounded-lg bg-emerald-500/10 flex items-center justify-center shrink-0">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-white text-xs font-mono">{p.resource}</span>
                    <span className="text-emerald-400 text-xs font-bold">${p.cost}</span>
                  </div>
                  {p.txHash && (
                    <a href={explorerTxUrl(p.txHash)} target="_blank" rel="noopener noreferrer"
                      className="flex items-center gap-1 mt-0.5 text-[10px] text-brand-400 hover:text-brand-300 font-mono">
                      <ExternalLink className="w-2.5 h-2.5" /> {shortHash(p.txHash)}
                    </a>
                  )}
                </div>
                {p.txHash && (
                  <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-brand-500/10 text-brand-400 font-semibold shrink-0">
                    ON-CHAIN
                  </span>
                )}
              </div>
            ))}
            {skipped.map((p, i) => (
              <div key={i} className="flex items-center gap-3 bg-red-500/5 border border-red-500/10 rounded-xl p-3">
                <div className="w-7 h-7 rounded-lg bg-red-500/10 flex items-center justify-center shrink-0">
                  <XCircle className="w-3.5 h-3.5 text-red-400" />
                </div>
                <span className="text-surface-400 text-xs font-mono flex-1">{p.resource}</span>
                <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-red-500/10 text-red-400 font-semibold">
                  AI SKIPPED
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ═══ Console Terminal — always visible ═══ */}
      {hasOutput && (
        <div className="console-bg rounded-2xl overflow-hidden">
          {/* Terminal header */}
          <div className="flex items-center justify-between px-4 py-2.5 border-b border-surface-200/20">
            <div className="flex items-center gap-2">
              <div className="w-2.5 h-2.5 rounded-full bg-red-500/70" />
              <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" />
              <div className="w-2.5 h-2.5 rounded-full bg-green-500/70" />
              <span className="ml-2 text-[10px] text-surface-500 font-mono flex items-center gap-1">
                <Terminal className="w-2.5 h-2.5" />
                {job.id}: "{job.query}"
              </span>
            </div>
            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
              isCompleted ? 'bg-emerald-500/10 text-emerald-400' :
              isRunning ? 'bg-yellow-500/10 text-yellow-400' :
              'bg-red-500/10 text-red-400'
            }`}>
              {isRunning ? '● LIVE' : isCompleted ? '✓ DONE' : 'FAILED'}
            </span>
          </div>

          {/* Terminal body — auto-scroll, color-coded */}
          <div ref={consoleRef} className="p-4 max-h-[400px] overflow-auto">
            <div className="space-y-0.5">
              {parsed.cleanText.split('\n').map((line, i) => {
                const isPhase = /PHASE|AGENT|FINAL ANSWER|════/i.test(line)
                const isBuy = /✅.*BUY|Payment confirmed|💰|PAID/i.test(line)
                const isSkip = /❌.*SKIP|SKIP/i.test(line)
                const isError = /✖|FAILED|ERROR|⚠/i.test(line)
                const isInfo = /│|┌|└|─|║|╔|╚|╠/i.test(line)
                const txMatch = line.match(/(0x[a-fA-F0-9]{64})/)

                return (
                  <div key={i} className={`text-[11px] font-mono leading-relaxed flex items-start gap-2 ${
                    isPhase ? 'text-cyan-400 font-bold' :
                    isBuy ? 'text-emerald-400' :
                    isSkip ? 'text-red-400' :
                    isError ? 'text-red-400' :
                    isInfo ? 'text-purple-300' :
                    'text-surface-400'
                  }`}>
                    <span className="text-surface-700 select-none w-8 text-right shrink-0 text-[10px]">{i + 1}</span>
                    <span className="flex-1 whitespace-pre-wrap break-all">
                      {line}
                      {txMatch && (
                        <a href={explorerTxUrl(txMatch[1])} target="_blank" rel="noopener noreferrer"
                          className="inline-flex items-center gap-0.5 ml-1.5 text-brand-400 hover:text-brand-300 align-middle">
                          <ExternalLink className="w-2.5 h-2.5" />
                        </a>
                      )}
                    </span>
                  </div>
                )
              })}
              {isRunning && (
                <div className="flex items-center gap-2 text-[11px] text-yellow-400 font-mono pt-2">
                  <Loader2 className="w-3 h-3 animate-spin" />
                  <span className="animate-pulse">▊</span>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ═══ Synthesized Report — appears BELOW console after completion ═══ */}
      {isCompleted && parsed.report && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="glass rounded-2xl overflow-hidden border border-brand-500/20"
        >
          {/* Report header */}
          <div className="flex items-center justify-between px-5 py-3 bg-brand-500/5 border-b border-brand-500/10">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-brand-500/10 flex items-center justify-center">
                <FileText className="w-3.5 h-3.5 text-brand-400" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-white">Synthesized Report</h3>
                <p className="text-[10px] text-surface-500">AI-generated analysis from purchased data sources</p>
              </div>
            </div>
            <button
              onClick={() => downloadPDF(parsed.report, `paycrawl-${job.id}.pdf`)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-brand-500/10 hover:bg-brand-500/20 text-brand-400 rounded-lg text-xs font-medium transition-all"
            >
              <Download className="w-3.5 h-3.5" /> PDF
            </button>
          </div>

          {/* Report content */}
          <div className="p-6 max-h-[700px] overflow-auto">
            <div className="prose prose-invert prose-sm max-w-none
              prose-headings:text-white prose-headings:font-bold
              prose-h1:text-xl prose-h1:border-b prose-h1:border-surface-200/20 prose-h1:pb-2
              prose-h2:text-lg prose-h2:text-brand-400
              prose-h3:text-base prose-h3:text-accent-400
              prose-p:text-white prose-p:leading-relaxed
              prose-strong:text-white prose-strong:font-semibold
              prose-li:text-white
              prose-code:text-brand-300 prose-code:bg-surface-50/50 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded
              prose-blockquote:border-brand-500 prose-blockquote:bg-brand-500/5
              prose-table:text-xs
              prose-th:text-white prose-th:bg-surface-50/50
              prose-td:text-white
              prose-a:text-brand-400
            ">
              <ReactMarkdown>{parsed.report}</ReactMarkdown>
            </div>
          </div>
        </motion.div>
      )}
    </motion.div>
  )
}
